### ISSUE TITLE
Android - Failed to Resolve

### ISSUE THREAD

**Issue by vaaneeunbnd** [libgdx/gdx-video#59] opened 2020-11-06 00:11 UTC
Hello, 

Hope your day is going well. I was trying to add the gdx-video library to the Gradle build file, however, I am getting the error message - Failed to resolve: com.badlogicgames.gdxvideo:gdx-video-android:1.9.12.

I would be grateful if someone can help me with this.

Thanks

**Comment by SimonIT** [comment] 2020-11-06 08:55
Sadly, there is nothing I can do about it. I want to upload it, but @Tom-Ski has to make some sonatype stuff to get it working.
I'm closing this, because this is a duplicate of #51

**Closed by SimonIT** 2020-11-06 08:55 UTC
