### ISSUE TITLE
Error running desktop player on Ubuntu 14.04

### ISSUE THREAD

**Issue by Mur4ik** [libgdx/gdx-video#4] opened 2015-03-24 10:56 UTC
Hi. Desktop version work great on Windows, but running the same project on Ubuntu get this error:

/usr/lib/jvm/java-7-oracle/bin/java: symbol lookup error: /tmp/jnigen/4185592305/libgdx-video-desktop.so: undefined symbol: __wrap_memcpy

**Comment by Robbiedobbie** [comment] 2015-03-24 11:14
Are you running 32bit or 64bit java?

**Comment by Mur4ik** [comment] 2015-03-24 11:49
32bit on x86 Ubuntu 14.04

**Comment by Robbiedobbie** [comment] 2015-03-26 15:34
I've been looking at the file through readelf, and indeed, the symbol seems to be undefined. For some reason, this only happened in the 32bit build. The 64bit version does have the symbol defined.

It could be that something is wrong in my local toolchain. I will put some further investigation into this. Unfortunately, I am currently really busy with exams, so I won't be able to look into it until the end of next week.

**Comment by Robbiedobbie** [comment] 2015-12-20 10:35
I'm sorry that I never continued on this issue. When actually trying myself locally, I couldn't reproduce the issue, which makes it hard to find out what is wrong.

Since it has been this long, I'm going to close this issue.

**Closed by Robbiedobbie** 2015-12-20 10:35 UTC
